### ISSUE TITLE
Attachear los productos generados en los releases

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1863]
En Pilas Bloques, cada vez que lanzamos un [nuevo release](https://github.com/Program-AR/pilas-bloques/releases) Travis adjunta los productos generados en él. Eso está buenísimo porque queda el historial de productos generados en github, fácilmente descargables. 

Esto es algo que estoy buscando hace tiempo, porque somos de hacer cambios que rompen la retrocompatibilidad, sobre todo con WGame. Y ahora mismo tengo un montón de juegos del cuatri pasado que la gente no puede ejecutar porque actualizaron la versión y rompe los juegos (y no tienen forma de descargarse una versión anterior).

**Comment by fdodino** [comment]
@PalumboN , ahí estuve mirando [el archivo travis de Pilas-Bloques](https://github.com/Program-AR/pilas-bloques/blob/develop/.travis.yml) y también [esta pregunta de Stack Overflow](https://stackoverflow.com/questions/51741317/travis-ci-deploy-jar-to-github-releases) y tengo ganas de ver si lo ponemos antes de liberar la versión 1.9.2 en estos días, así nos queda como versión histórica para los que tienen 32 bits.

**Comment by fdodino** [comment]
https://docs.travis-ci.com/user/deployment/releases/

**Comment by npasserini** [comment]
Creo que se puede tener lo mismo pero guardándolos automáticamente en el
S3. De hecho la parte difícil de eso está hecha, los releases se suben,
solamente hay que asegurarse de no pisar los viejos.

**Comment by fdodino** [comment]
Podemos armar una página con links a S3 que tienen este formato:

https://wollokversions.s3-us-west-2.amazonaws.com/v1.9.0/wollok-win32.win32.x86_64.zip

Es decir:

`https://wollokversions.s3-us-west-2.amazonaws.com/vX.Y.Z/ejecutableEnSO_XXbits.zip`

sabiendo que a partir de la versión 2.0 ya no tenemos 32 bits

**Comment by fdodino** [comment]
Dejo acá el script de travis que agregué al final antes de env global, por si en algún momento lo queremos reflotar.

```yml
- provider: releases
  skip_cleanup: true
  api_key:
    secure: ZGDMxFYXbp/LgNqtGourJXgQS2itBxHWzLqDKnSd1YV6sDHnYzvrq8aCoLHujMCI0yLkRAI12raylJkXHzQHcN3JDF0SyJostz59x1KEJ4cpv8K5bb2bs8BsV/BuZlQssu6yqqgaIXOALF52wUGgVg8nBjWA0LdRL5DDFs8ExR0=
  file_glob: true    
  file: results-products/*.zip
  on:
    tags: true
    all_branches: true  
    repo: uqbar-project/wollok
```
